import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { TRPCReactProvider } from '@/trpc/client'

import React from 'react'
import "./globals.css";
interface Props {
    children: React.ReactNode
};


const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Meet.AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
    <html lang="en">
      <body
        className={`${inter.className} antialised`}>
        {children}
        </body>
    </html>
    </TRPCReactProvider>
  )

}
