import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { TRPCReactProvider } from '@/trpc/client'

import React from 'react'
import "./globals.css";
import { Toaster } from 'sonner';
interface Props {
    children: React.ReactNode
};


const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Meet.AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className} antialised`}>
            <Toaster />
          {children}
          </body>
      </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  )

}
